### PR TITLE
Added implementation of Marshaler interface for Point and UUID data types

### PR DESCRIPTION
**Pull request by bigmate**

### CODE REVIEW

**Comment by jackc** [comment]
Can point parsing be implemented in terms of `DecodeText`? That would eliminate the regexp dependency.

**Comment by bigmate** [comment]
> Can point parsing be implemented in terms of `DecodeText`? That would eliminate the regexp dependency.

Oh I see, yes, you are right.
Let me do that

**Comment by bigmate** [comment]
Done!

**Comment by jackc** [comment]
👍

**Pull request merged**
