### PR TITLE
Fixes #11 -- support initializing Array types from a slice of the value

### LINKED ISSUE #11: More efficient API for creating TextArray (probably other arrays too?)
Right now I've got code like:

```go
ids := []string{}
for obj := range objs {
    ids = append(ids, obj.id)
}

idsArray := &pgtype.TextArray{}
idsArray.Set(ids)
tx.Query(ctx, `SELECT * FROM TABLE WHERE id = ANY($1)`, idsArray)
```

The `TextArray` API here is relatively inefficient because it requires allocating a new slice of `[]Text`. I can manually create an instance, but this requires knowing how to populate the `Dimensions` field. Worse, there's no easy way to reuse the allocated memory, if I'm doing multiple queries.

I think the right solution here would be if `TextArray.Set()` supported intialization from `[]pgtype.Text`.

I believe this would be a straightforward addition to the API, and I'd be happy to send a PR if you're interested. The code probably looks something like:

```go
case []Text:
    if value == nil {
        *dst = TextArray{Status: Null}
    } else if len(value) == 0 {
        *dst = TextArray{Status: Present}
    } else {
        *dst = TextArray{Elements: value, Dimensions: []ArrayDimension{{Length: int32(len(value)), LowerBound: 1}}, Status: Present}
    }
```
inserted at https://github.com/jackc/pgtype/blob/master/text_array.go#L44

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by jackc** [comment]
Thanks! Merged with some extra fixes to preexisting problems that this change revealed.

**Comment by alex** [comment]
Thanks for the review + merge! Looking forward to pgx upgrading to this :-)

**Comment by gaffneyc** [comment]
Noticed that this changes EncodeText, EncodeBinary, and Value to be on *T instead of T which seems like a partial reversion of a8802b16cc593842f5c69b0f7cfb0de11d5cd3a8.

**Comment by jackc** [comment]
@gaffneyc Doesn't be36a7e14b3e4f6938baa727139d6fa95f6ad1fe correct that? I noticed that and (attempted) to correct it prior to merging. The only change of *T / T was on TstzrangeArray and that change was to harmonize it with a8802b16cc593842f5c69b0f7cfb0de11d5cd3a8.

**Comment by gaffneyc** [comment]
Ah.... sorry, it did. I was just looking at the changelog and the PR and didn't look at changes after it.

**Pull request merged**
