### PR TITLE
Fix: escaped strings when they start or end with a newline char

### PR DESCRIPTION
**Pull request by stephane-martin**
(jackc/pgtype#86)

### CODE REVIEW

**Comment by jackc** [comment]
Would this problem also manifest with a newline in the middle? I'm thinking it might be necessary to quote if a newline is anywhere in the string -- not just at the beginning or end?

**Comment by stephane-martin** [comment]
I don't think so. This has to do with the textual representation of arrays and their parsing by pg. Looks like newlines are considered whitespace.

```
# SELECT UNNEST(('{aaa,bbb'||E'\n'||'}')::text[]);
│ unnest │
│ aaa    │
│ bbb    │

# SELECT UNNEST(('{aaa,"bbb'||E'\n'||'"}')::text[]);
│ unnest │
│ aaa    │
│ bbb   ↵│
│        │
```

**Comment by stephane-martin** [comment]
but:

```
ics=# SELECT UNNEST(('{aaa,bbb'||E'\n'||'c}')::text[]);
│ unnest │
│ aaa    │
│ bbb   ↵│
│ c      │
```

So whitespaces in the middle do not look like a problem.

**Comment by stephane-martin** [comment]
tabs too do have the problem:

```
# SELECT UNNEST(('{aaa,bbb'||E'\t'||'}')::text[]);
│ unnest │
│ aaa    │
│ bbb    │

ics=# SELECT UNNEST(('{aaa,"bbb'||E'\t'||'"}')::text[]);
│  unnest  │
│ aaa      │
│ bbb      │
```

**Comment by stephane-martin** [comment]
I've not been able to locate inside postgres source code where the array parsing happens, but:
- https://github.com/postgres/postgres/blob/REL_12_STABLE/src/backend/parser/README#L12
- https://github.com/postgres/postgres/blob/REL_12_STABLE/src/backend/parser/scansup.c#L224

So I guess for this issue, `\t`, `\n`, `\r`, `\f` should be considered whitespace.

**Comment by jackc** [comment]
Thanks!

**Pull request merged**
