### PR TITLE
Fix 490: Add jsonb arrays for pgx v4

### PR DESCRIPTION
**Pull request by laskoviymishka**

### CODE REVIEW

**Comment by laskoviymishka** [comment]
@jackc could you plz review (also with -  https://github.com/jackc/pgx/pull/776 )

**Comment by jackc** [comment]
Array types are generated programmatically. Can you generate this with typed_array_gen.sh?

**Comment by laskoviymishka** [comment]
Didn't know about it, fixed

**Comment by laskoviymishka** [comment]
@jackc could you plz revew

**Pull request merged**
